server:
  port: 8001

eureka:
  instance:
    host: localhost
    port: 7001
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    # needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.host}:${eureka.instance.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          searchLocations : file:///${RESOURCES_DIR}/services/{application}
