spring:
  application:
    name: config-server

management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*" # To expose all endpoints
  endpoint:
    health:
      show-details: ALWAYS
    env:
      show-values: ALWAYS # To unmasked the value in env
  security:
    enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10 # how often client sends heartbeat to server. This value should be less than leaseExpirationDurationInSeconds
    health-check-url-path: /actuator/health
    # The startup value changing forces the cache to refresh. This helps other microservices detect service restarts.
    metadata-map:
      startup: ${random.int}
  client:
    registryFetchIntervalSeconds: 30 # Fetch registry every 30 seconds
    register-with-eureka: true