server:
  port: 8000

eureka:
  instance:
    host: localhost
    port: 7000
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.host}:${eureka.instance.port}/eureka/

spring:
  cloud:
    config:
      server:
        native:
          searchLocations : file:///${RESOURCES_DIR}/services/{application}
