server:
  port: 21002

spring:
  datasource:
    sqlserver:
      url: jdbc:sqlserver://himanshu:1433;databaseName=dev2;encrypt=false
      username: springboot
      password: admin
    mysql:
      url: jdbc:mysql://himanshu:3306/dev2?useSSL=false
      username: springboot
      password: admin
