server:
  port: 21001

spring:
  datasource:
    sqlserver:
      url: jdbc:sqlserver://himanshu:1433;databaseName=dev1;encrypt=false
      username: springboot
      password: admin
    mysql:
      url: jdbc:mysql://himanshu:3306/dev1?useSSL=false
      username: springboot
      password: admin