eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    # needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    env:
      show-values: ALWAYS # To unmasked the value in env
  security:
    enabled: false
