server:
  port: 9002

eureka:
  instance:
    preferIpAddress: true
    host: localhost
    port: 7002
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.host}:${eureka.instance.port}/eureka/