server:
  port: 9000

eureka:
  instance:
    preferIpAddress: true
    host: localhost
    port: 7000
  client:
    registerWithEureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.host}:${eureka.instance.port}/eureka/

