CREATE TABLE Customer (
    CUSTOMER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ADDRESS VARCHAR(255),
    CITY VARCHAR(255),
    COUNTRY VARCHAR(255),
    EMAIL VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    PHONE_NUMBER VARCHAR(255),
    POSTAL_CODE VARCHAR(255),
    STATE VARCHAR(255)
);