CREATE TABLE Transactions (
    TRANSACTION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID BIGINT,
    TRANSACTION_DATE VARCHAR(255),
    PRODUCT_ID VARCHAR(255),
    QUANTITY INT,
    UNIT_PRICE DECIMAL(10, 2),
    TOTAL_PRICE DECIMAL(10, 2),
    PAYMENT_METHOD VARCHAR(255),
    STATUS VARCHAR(255),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer(CUSTOMER_ID)
);