server:
  port: 7000

eureka:
  instance:
    hostname: localhost # hostname where Eureka server run
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # Eureka server url
